### ISSUE TITLE
TK#10 DER (Diagrama de Entidad-Relación)

### ISSUE THREAD

**Issue by JDGA1997** [JDGA1997/ASPRA-Movil#10]
### Crear un DER (Diagrama de Entidad-Relación) que represente la estructura de la base de datos actualizada.

> [Ej. Diagrama de Entidad-Relación](https://www.lucidchart.com/pages/es/que-es-un-diagrama-entidad-relacion)

**Comment by MelanieR24** [comment]
ya lo acabo de subir al DER
